server:
  port: 8082

spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt-secret: ShNjmvdkfBfw9eZhLkbV5nhAX00M8rUesgjHwuCFJNvRebkqiwDw04LwUFScS7ROVj6mAmeFI0dZ29UNATGvQA==

product-service:
  url: http://localhost:8081/products


